name: Run Backend App

on:
  push:
    branches:
      - main  # Możesz zmienić na inną gałąź

jobs:
  start-backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend  # Przechodzimy do folderu backend

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run backend
        run: npm start
